language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - rbx-18mode
  - rbx-19mode
  - jruby-18mode
  - jruby-19mode
  - jruby-head
env:
  - RSPEC="2.5.0"
  - RSPEC="3.1.0"
script: "bundle exec rake spec:ci"
