language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.1.5
  - jruby-19mode
  - jruby-head
  - rbx-19mode
env:
  - RSPEC="2.5.0"
  - RSPEC="3.1.0"
script: "bundle exec rake spec:ci"
services:
  - rabbitmq
notifications:
  recipients:
    - markizko@gmail.com
